name: Docker image CI for GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required for GHCR push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u origamini --password-stdin

      - name: Build Docker image
        run: docker build . -t ghcr.io/origamini/nextjs-dummy:latest

      - name: Push Docker image
        run: docker push ghcr.io/origamini/nextjs-dummy:latest
